language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t ramaditya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ramaditya/docker-react npm run test