version: '3'
services:
    tests:
        build:
            context: .
            dockerfile: Dockerfile
        
        # volumes:
        #         - /app/node_modules
        #         - .:/app
            
        # command: ["npm", "run", "test"]


        